template_path: templates/bridge-exporter.yaml
stack_name: bridge-exporter-{{ environment_variable.TRAVIS_BRANCH }}
parameters:
  AttachmentsBucket: {{ environment_variable.AttachmentsBucket_prod }}
  AwsDefaultVpcId: {{ environment_variable.AwsDefaultVpcId_prod }}
  AwsSnsNotificationEndpoint: {{ environment_variable.AwsSnsNotificationEndpoint_prod }}
  AwsSolutionStackName: {{ environment_variable.AwsSolutionStackName }}
  BridgeEnv: {{ environment_variable.BridgeEnv_prod }}
  BridgeUser: {{ environment_variable.BridgeUser }}
  BridgeWorkerEmail: {{ environment_variable.BridgeWorkerEmail_prod }}
  BridgeWorkerStudy: {{ environment_variable.BridgeWorkerStudy_prod }}
  BridgeWorkerPassword: {{ environment_variable.BridgeWorkerPassword_prod }}
  EC2InstanceType: t2.micro
  Env: {{ environment_variable.Env_prod }}
  NewRelicAppName: bridge-exporter-{{ environment_variable.TRAVIS_BRANCH }}
  NewRelicLicenseKey: {{ environment_variable.NewRelicLicenseKey }}
  RecordIdsBucket: {{ environment_variable.RecordIdsBucket_prod }}
  SynapseApiKey: {{ environment_variable.SynapseApiKey_prod }}
  SynapseGetColumnModelsRateLimitPerMinute: "{{ environment_variable.SynapseGetColumnModelsRateLimitPerMinute }}"
  SynapsePrincipalId: "{{ environment_variable.SynapsePrincipalId_prod }}"
  SynapseUser: {{ environment_variable.SynapseUser_prod }}
  ThreadPoolWorkerCount: "{{ environment_variable.ThreadPoolWorkerCount }}"
