template_path: templates/bridge-exporter.yaml
stack_name: bridge-exporter-prod
parameters:
  AttachmentsBucket: org-sagebridge-attachment-prod
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridge-exporter-prod@sagebase.org
  AwsSolutionStackName: '64bit Amazon Linux 2018.03 v3.0.1 running Tomcat 8 Java 8'
  BridgeEnv: prod
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+exporter@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridge-exporter-prod/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: production
  NewRelicAppName: bridge-exporter-prod
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RecordIdsBucket: org-sagebridge-exporter-recordids-prod
  SynapseApiKey: !ssm /bridge-exporter-prod/SynapseApiKey
  SynapseGetColumnModelsRateLimitPerMinute: '6'
  SynapsePrincipalId: '3325672'
  SynapseUser: BridgeExporter
  ThreadPoolWorkerCount: '4'
