template_path: templates/bridge-exporter.yaml
stack_name: bridge-exporter-develop
parameters:
  AttachmentsBucket: org-sagebridge-attachment-develop
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridge-exporter-develop@sagebase.org
  AwsSolutionStackName: '64bit Amazon Linux 2017.09 v2.7.5 running Tomcat 8 Java 8'
  BridgeEnv: dev
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+worker@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridge-exporter-develop/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: develop
  NewRelicAppName: bridge-exporter-develop
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RecordIdsBucket: org-sagebridge-exporter-recordids-develop
  SynapseApiKey: !ssm /bridge-exporter-develop/SynapseApiKey
  SynapseGetColumnModelsRateLimitPerMinute: '6'
  SynapsePrincipalId: '3330889'
  SynapseUser: BridgeExporterDev
  ThreadPoolWorkerCount: '4'
