template_path: bridge-exporter.yaml
stack_name: bridge-exporter-uat
parameters:
  AttachmentsBucket: org-sagebridge-attachment-uat
  AwsDefaultVpcId: vpc-9c70bbf9
  AwsSnsNotificationEndpoint: bridge-exporter-uat@sagebase.org
  BridgeEnv: uat
  BridgeUser: heroku
  BridgeWorkerEmail: bridgeit+exporter@sagebase.org
  BridgeWorkerStudy: api
  BridgeWorkerPassword: !ssm /bridge-exporter-uat/BridgeWorkerPassword
  EC2InstanceType: t2.micro
  Env: staging
  NewRelicAppName: bridge-exporter-uat
  NewRelicLicenseKey: !ssm /infra/NewRelicLicenseKey
  RecordIdsBucket: org-sagebridge-exporter-recordids-uat
  SynapseApiKey: !ssm /bridge-exporter-uat/SynapseApiKey
  SynapseGetColumnModelsRateLimitPerMinute: '6'
  SynapsePrincipalId: '3327942'
  SynapseUser: BridgeExporterStaging
  ThreadPoolWorkerCount: '4'
