template_path: templates/bridge-exporter.yaml
stack_name: bridge-exporter-{{ environment_variable.TRAVIS_BRANCH }}
parameters:
  AttachmentsBucket: {{ environment_variable.AttachmentsBucket_uat }}
  AwsDefaultVpcId: {{ environment_variable.AwsDefaultVpcId_uat }}
  AwsSnsNotificationEndpoint: {{ environment_variable.AwsSnsNotificationEndpoint_uat }}
  AwsSolutionStackName: {{ environment_variable.AwsSolutionStackName }}
  BridgeEnv: {{ environment_variable.BridgeEnv_uat }}
  BridgeUser: {{ environment_variable.BridgeUser }}
  BridgeWorkerEmail: {{ environment_variable.BridgeWorkerEmail_uat }}
  BridgeWorkerStudy: {{ environment_variable.BridgeWorkerStudy_uat }}
  BridgeWorkerPassword: {{ environment_variable.BridgeWorkerPassword_uat }}
  EC2InstanceType: t2.micro
  Env: {{ environment_variable.Env_uat }}
  NewRelicAppName: bridge-exporter-{{ environment_variable.TRAVIS_BRANCH }}
  NewRelicLicenseKey: {{ environment_variable.NewRelicLicenseKey }}
  RecordIdsBucket: {{ environment_variable.RecordIdsBucket_uat }}
  SynapseApiKey: {{ environment_variable.SynapseApiKey_uat }}
  SynapseGetColumnModelsRateLimitPerMinute: "{{ environment_variable.SynapseGetColumnModelsRateLimitPerMinute }}"
  SynapsePrincipalId: "{{ environment_variable.SynapsePrincipalId_uat }}"
  SynapseUser: {{ environment_variable.SynapseUser_uat }}
  ThreadPoolWorkerCount: "{{ environment_variable.ThreadPoolWorkerCount }}"
